In [5]:
import numpy as np
import pandas as pd

#import pickle to dump extracted features 
import pickle

In [7]:
df = pd.read_csv('./terms_with_sentences.csv')
df.head()

Sents      Terms
0                                                NaN  acquittal
1                                                NaN  judgement
2                                                NaN  defendant
3  volutpat at tellus at urna condimentum mattis ...  affidavit
4  or officer having authority to administer oath...  appellate

In [10]:
df.dropna(inplace=True)

In [18]:
df['Terms'].value_counts()

court                 51
jury                  16
judge                 15
evidence              13
defendant             13
lawsuit                9
appellate              8
testimony              7
judgement              7
answer                 7
parties                7
witness                6
plaintiff              5
complaint              5
opinion                4
record                 4
bankruptcy             4
appeal                 4
jurisdiction           3
petit jury             3
transcript             3
discovery              3
clerk of court         2
remand                 2
settlement             2
issue                  2
warrant                2
reverse                2
mistrial               2
brief                  2
                      ..
jurisprudence          1
case law               1
charge to the jury     1
conviction             1
arraignment            1
sidebar                1
common law             1
oral argument          1
counterclaim           1


In [82]:
#Split the data into train & test sets
from sklearn.model_selection import train_test_split

X = df['Sents']
y = df['Terms']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [90]:
#vectorize the data, then train and fit a model
import sklearn.decomposition
import sklearn.feature_selection

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

#Build model
'''model = Pipeline([
                  ('tfidf', TfidfVectorizer(max_df=0.5, max_features=100,min_df=2, use_idf=True)), 
                  ('clf', LinearSVC()),
                  ('classify', sklearn.linear_model.LogisticRegressionCV()),
                                   
])'''


model = sklearn.pipeline.Pipeline([
    #('pca', sklearn.decomposition.PCA()),
    ('tfidf', TfidfVectorizer(max_df=0.5, max_features=100,min_df=2, use_idf=True)),
    ('classify', sklearn.linear_model.LogisticRegressionCV()),
    #('clf', LinearSVC()),
])

model.fit(X_train, y_train)

/home/shaitender/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.5, max_features=100, min_df=2,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
  ...2', random_state=None,
           refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=0))])

In [92]:
# Form a prediction set
predictions = model.predict(X_test)

In [94]:
#cm
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [93]:
print(metrics.accuracy_score(y_test,predictions))

0.19444444444444445


In [95]:
print(metrics.classification_report(y_test,predictions))

                        precision    recall  f1-score   support

             affidavit       0.00      0.00      0.00         1
                answer       0.00      0.00      0.00         1
                appeal       0.00      0.00      0.00         0
           arraignment       0.00      0.00      0.00         1
            bankruptcy       0.00      0.00      0.00         1
       capital offense       0.00      0.00      0.00         1
    charge to the jury       0.00      0.00      0.00         1
             complaint       0.00      0.00      0.00         1
            conviction       0.00      0.00      0.00         1
               counsel       0.00      0.00      0.00         1
                 court       0.20      0.88      0.33        16
             defendant       0.00      0.00      0.00         4
            deposition       0.00      0.00      0.00         1
             discovery       0.00      0.00      0.00         1
              evidence       0.00      

/home/shaitender/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/shaitender/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [96]:
# pickle model
from sklearn.externals import joblib
joblib.dump(model, "Phrase_Extractor.pickle")

['Phrase_Extractor.pickle']